from selenium.webdriver.common.by import By

programs_button = (By.CSS_SELECTOR, '[class="small-box bg-red"]')
work_button = (By.CSS_SELECTOR, '[class="small-box bg-yellow"]')
measurement_button = (By.CSS_SELECTOR, '[class="small-box bg-aqua"]')
exercises_button = (By.CSS_SELECTOR, '[class="small-box bg-green"]')
table_text = (By.CSS_SELECTOR, '[class="btn btn-success pull-right"]')
wme_text = (By.CSS_SELECTOR, '[class="content-header"]')
setting_button = (By.CSS_SELECTOR, '[class="btn btn-primary btn-block"]')
my_programs_button = (By.XPATH, '//*[@id="solar"]//li[3]/a')
save_button = (By.XPATH, '//button')
program_name_field = (By.ID, 'field_name_u')
setting_program_button = (By.XPATH, '//*[@id="edit-program"]//ul/li[1]/a')
alert_message = (By.CSS_SELECTOR, '#object-form > div > div.box-body > div:nth-child(2) > div')
program_text_field = (By.ID, 'field_content_u')
combobox = (By.ID, 'field_category')
work_button = (By.XPATH, '//*[@id="solar"]/div[2]//div/div/ul/li[2]/a')
new_day_button = (By.CSS_SELECTOR, "[class='btn btn-success']")
days_table = (By.CSS_SELECTOR, '[class="sortable-item day"]')
delete_day_button = (By.CSS_SELECTOR, 'a.btn.btn-xs.btn-danger > span')
add_exercise_button = (By.CSS_SELECTOR, '[class="hidden-xs"]')
exercises_check_box = (By.CSS_SELECTOR, '[class="icheckbox_minimal-blue"]')
save_exercises_button = (By.CSS_SELECTOR, '[class="btn btn-primary"]')
new_exercise = (By.CSS_SELECTOR, '[class="exercise-info pull-left"]')
edit_button = (By.XPATH, '//div[1]/div/a[2]/span')
exercise_name = (By.XPATH, '//div/div/div/div[3]/div/div[1]/input[2]')
save_edit_text_button = (By.CSS_SELECTOR, '[class="btn btn-primary pull-right"]')
exercise_name_two = (By.XPATH, '//div[1]/h3/span')
my_workouts_button = (By.XPATH, '//ul/li[4]/a')
add_new_workout_button = (By.CSS_SELECTOR, '[class="btn btn-success pull-right open-modal"]')
save_new_workout_button = (By.CSS_SELECTOR, '[class="btn btn-primary"]')
workout_table = (By.CSS_SELECTOR, '[class="box-header with-border day-title"]')
delete_workout_button = (By.XPATH, '//div[1]/div/a[2]')
